alter table public.clients
add column if not exists company_name text,
add column if not exists primary_payment_method text default 'EFT',
add column if not exists currency text default 'ZAR',
add column if not exists invoice_language text default 'English',
add column if not exists vat_number text,
add column if not exists opening_balance numeric default 0,
add column if not exists opening_balance_as_of date,
add column if not exists title text,
add column if not exists first_name text,
add column if not exists middle_name text,
add column if not exists last_name text,
add column if not exists suffix text,
add column if not exists phone_number text,
add column if not exists mobile_number text,
add column if not exists other_phone text,
add column if not exists fax_number text,
add column if not exists cc_email text,
add column if not exists bcc_email text,
add column if not exists website text,
add column if not exists marketing_consent boolean not null default false,
add column if not exists billing_address_line_1 text,
add column if not exists billing_address_line_2 text,
add column if not exists billing_city text,
add column if not exists billing_state text,
add column if not exists billing_postal_code text,
add column if not exists billing_country text,
add column if not exists delivery_address_line_1 text,
add column if not exists delivery_address_line_2 text,
add column if not exists delivery_city text,
add column if not exists delivery_state text,
add column if not exists delivery_postal_code text,
add column if not exists delivery_country text,
add column if not exists stock_holding_enabled boolean not null default false,
add column if not exists stock_holding_agreement_signed boolean not null default false,
add column if not exists stock_holding_agreement_signed_date date,
add column if not exists stock_holding_agreement_reference text,
add column if not exists stock_holding_review_date date,
add column if not exists credit_agreement_signed boolean not null default false,
add column if not exists credit_agreement_signed_date date,
add column if not exists credit_agreement_reference text,
add column if not exists storage_grace_period_days integer not null default 0,
add column if not exists max_storage_period_days integer not null default 0,
add column if not exists storage_fee_applies boolean not null default false,
add column if not exists storage_fee_type text default 'None',
add column if not exists storage_fee_rate numeric default 0,
add column if not exists deposit_required_percent numeric default 0,
add column if not exists minimum_monthly_release_quantity numeric default 0,
add column if not exists minimum_monthly_release_unit text default 'units',
add column if not exists minimum_release_quantity numeric default 0,
add column if not exists delivery_charge_policy text default 'Charge Every Release',
add column if not exists release_approval_required boolean not null default true,
add column if not exists portal_enabled boolean not null default false,
add column if not exists portal_view_quotes boolean not null default true,
add column if not exists portal_view_invoices boolean not null default true,
add column if not exists portal_view_stock boolean not null default true,
add column if not exists portal_request_release boolean not null default false;
