/**
 * Email service — thin client over the `send-payslip` Supabase Edge Function.
 *
 * The function relays HTML emails through Resend. This keeps the API key on the
 * server (never in the browser bundle) and the call authenticated as the signed-in
 * dashboard user.
 */

import { AppSettingsCompany, Payslip, PayrollRun } from '../types';
import { supabase } from './supabase';

export interface OutgoingEmail {
  to: string;
  subject: string;
  html: string;
  cc?: string;
}

export interface SendResult {
  sent: number;
  total: number;
  results: { to: string; ok: boolean; error?: string }[];
  error?: string;
}

function money(n: number): string {
  return (Number(n) || 0).toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

/** Build a clean, email-client-safe HTML payslip (inline styles, simple table). */
export function buildPayslipHtml(slip: Payslip, run: PayrollRun, company?: AppSettingsCompany): string {
  const row = (label: string, value: string, strong = false) =>
    `<tr>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;${strong ? 'font-weight:700;' : ''}">${label}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right;${strong ? 'font-weight:700;' : ''}">${value}</td>
    </tr>`;
  return `
  <div style="font-family:Arial,Helvetica,sans-serif;max-width:560px;margin:0 auto;color:#1a1a1a;">
    <div style="display:flex;justify-content:space-between;border-bottom:2px solid #db5a1f;padding-bottom:10px;margin-bottom:14px;">
      <div><strong style="font-size:18px;">${company?.name || 'JomoPak'}</strong><br/>
        <span style="font-size:11px;color:#666;">${company?.legalName || ''}</span></div>
      <div style="text-align:right;"><strong>PAYSLIP</strong><br/>
        <span style="font-size:11px;color:#666;">${run.periodLabel} · paid ${run.payDate}</span></div>
    </div>
    <p style="font-size:13px;margin:0 0 12px;">Dear ${slip.employeeName},</p>
    <p style="font-size:13px;margin:0 0 14px;">Please find your payslip for <strong>${run.periodLabel}</strong> below.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;">
      ${row('Basic pay', money(slip.basicSalary))}
      ${row('Allowances', money(slip.allowances))}
      ${row('Gross pay', money(slip.grossPay), true)}
      ${row('PAYE', '-' + money(slip.paye))}
      ${row('UIF', '-' + money(slip.uifEmployee))}
      ${row('Other deductions', '-' + money(slip.otherDeductions))}
      ${row('Net pay', 'R ' + money(slip.netPay), true)}
    </table>
    <p style="font-size:11px;color:#666;margin-top:12px;">Employer contributions (not deducted): UIF ${money(slip.uifEmployer)} · SDL ${money(slip.sdl)}</p>
    <p style="font-size:11px;color:#999;margin-top:18px;border-top:1px solid #eee;padding-top:10px;">
      This payslip was generated by ${company?.name || 'JomoPak'}. If anything looks wrong, please contact payroll.
    </p>
  </div>`;
}

/** Send a batch of emails via the edge function. Never throws — returns a result. */
export async function sendEmails(emails: OutgoingEmail[]): Promise<SendResult> {
  if (emails.length === 0) {
    return { sent: 0, total: 0, results: [], error: 'No recipients with an email address.' };
  }
  try {
    const { data, error } = await supabase.functions.invoke('send-payslip', { body: { emails } });
    if (error) {
      // Try to surface the function's JSON error message if present.
      let message = error.message || 'Email service call failed.';
      try {
        const ctx = (error as { context?: { json?: () => Promise<unknown> } }).context;
        if (ctx?.json) {
          const parsed = (await ctx.json()) as { error?: string };
          if (parsed?.error) message = parsed.error;
        }
      } catch {
        /* ignore */
      }
      return { sent: 0, total: emails.length, results: [], error: message };
    }
    const payload = (data || {}) as SendResult;
    return {
      sent: payload.sent ?? 0,
      total: payload.total ?? emails.length,
      results: payload.results ?? [],
      error: payload.error,
    };
  } catch (err) {
    return { sent: 0, total: emails.length, results: [], error: String(err) };
  }
}
