import {
  AppData,
  ArtworkRecord,
  Client,
  CostProfile,
  CustomerStockRelease,
  DispatchRecord,
  FinishedGoodsStock,
  JobCard,
  Lead,
  Machine,
  MaterialOrderRequest,
  MaterialReceipt,
  PaperLog,
  PaperRate,
  PricingTier,
  Product,
  ProductionLogEntry,
  QuoteEstimate,
  SparePart,
  StockChangeLog,
  Supplier,
  WasteEntry,
} from '../types';
import { supabase } from './supabase';

const MISSING_TABLE = '42P01';

async function safeSelect(table: string) {
  const result = await supabase.from(table).select('*').order('created_at', { ascending: false });
  if (result.error && result.error.code !== MISSING_TABLE) {
    throw result.error;
  }
  return result.data ?? [];
}

async function safeUpsert(table: string, rows: Record<string, unknown>[]) {
  if (!rows.length) {
    return;
  }
  const result = await supabase.from(table).upsert(rows);
  if (result.error && result.error.code !== MISSING_TABLE) {
    throw result.error;
  }
}

function mapSupplier(row: any): Supplier {
  const contacts = Array.isArray(row.contacts)
    ? row.contacts.map((contact: any, index: number) => ({
        id: contact.id ?? `supplier-contact-${row.id}-${index}`,
        fullName: contact.fullName ?? contact.full_name ?? '',
        role: contact.role ?? '',
        phone: contact.phone ?? '',
        email: contact.email ?? '',
        isPrimary: Boolean(contact.isPrimary),
      }))
    : [];
  const certifications = Array.isArray(row.certifications)
    ? row.certifications.map((certification: any, index: number) => ({
        id: certification.id ?? `supplier-cert-${row.id}-${index}`,
        type: certification.type ?? 'FSC',
        certificateNumber: certification.certificateNumber ?? certification.certificate_number ?? '',
        issuedDate: certification.issuedDate ?? certification.issued_date ?? '',
        expiryDate: certification.expiryDate ?? certification.expiry_date ?? '',
        reviewFrequencyMonths: Number(certification.reviewFrequencyMonths ?? certification.review_frequency_months ?? 12),
        reminderDays: Number(certification.reminderDays ?? certification.reminder_days ?? 30),
        status: certification.status ?? 'Active',
        notes: certification.notes ?? '',
      }))
    : [];
  const suppliedProducts = Array.isArray(row.supplied_products)
    ? row.supplied_products.map((item: any, index: number) => ({
        id: item.id ?? `supplier-product-${row.id}-${index}`,
        productId: item.productId ?? item.product_id ?? '',
        productName: item.productName ?? item.product_name ?? '',
        supplierSku: item.supplierSku ?? item.supplier_sku ?? '',
        defaultPrice: Number(item.defaultPrice ?? item.default_price ?? 0),
        currency: item.currency ?? 'ZAR',
        minimumOrderQuantity: Number(item.minimumOrderQuantity ?? item.minimum_order_quantity ?? 0),
        leadTimeDays: Number(item.leadTimeDays ?? item.lead_time_days ?? 0),
        lastQuotedDate: item.lastQuotedDate ?? item.last_quoted_date ?? '',
        active: item.active !== false,
      }))
    : [];

  return {
    id: row.id,
    name: row.name,
    contactPerson: row.contact_person ?? '',
    phone: row.phone ?? '',
    email: row.email ?? '',
    contacts,
    address: row.address ?? '',
    billingAddress: row.billing_address ?? '',
    city: row.city ?? '',
    country: row.country ?? '',
    website: row.website ?? '',
    supplierType: row.supplier_type ?? 'General',
    certificateCode: row.certificate_code ?? '',
    accountNumber: row.account_number ?? '',
    paymentTerms: row.payment_terms ?? '',
    creditLimit: Number(row.credit_limit ?? 0),
    currentBalance: Number(row.current_balance ?? 0),
    currency: row.currency ?? 'ZAR',
    isAlsoClient: Boolean(row.is_also_client),
    linkedClientId: row.linked_client_id ?? '',
    linkedClientName: row.linked_client_name ?? '',
    lastCheckInDate: row.last_check_in_date ?? '',
    nextReviewDate: row.next_review_date ?? '',
    reviewFrequencyMonths: Number(row.review_frequency_months ?? 12),
    internalOwner: row.internal_owner ?? '',
    certifications,
    suppliedProducts,
    notes: row.notes ?? '',
    active: row.active !== false,
  };
}

function mapMachine(row: any): Machine {
  return {
    id: row.id,
    name: row.name,
    code: row.code ?? '',
    department: row.department ?? '',
    processType: row.process_type ?? '',
    status: row.status ?? 'Active',
    notes: row.notes ?? '',
    active: row.active !== false,
  };
}

function mapQuoteEstimate(row: any): QuoteEstimate {
  return {
    id: row.id,
    quoteNumber: row.quote_number,
    quickbooksEstimateNumber: row.quickbooks_estimate_number ?? '',
    createdAt: row.created_at,
    quoteDate: row.quote_date,
    linkedLeadId: row.linked_lead_id ?? '',
    linkedLeadNumber: row.linked_lead_number ?? '',
    salesOwnerName: row.sales_owner_name ?? '',
    clientId: row.client_id ?? '',
    clientName: row.client_name ?? '',
    productId: row.product_id ?? '',
    productName: row.product_name ?? '',
    pricingTierId: row.pricing_tier_id ?? '',
    pricingTierName: row.pricing_tier_name ?? '',
    paperRateId: row.paper_rate_id ?? '',
    paperRateName: row.paper_rate_name ?? '',
    costProfileId: row.cost_profile_id ?? '',
    costProfileName: row.cost_profile_name ?? '',
    quantity: Number(row.quantity ?? 0),
    sizeSpec: row.size_spec ?? '',
    handleType: row.handle_type ?? 'None',
    printMethod: row.print_method ?? 'Auto',
    colors: Number(row.colors ?? 0),
    unitCost: Number(row.unit_cost ?? 0),
    quotedUnitPrice: Number(row.quoted_unit_price ?? 0),
    totalQuote: Number(row.total_quote ?? 0),
    status: row.status ?? 'Draft',
    notes: row.notes ?? '',
  };
}

function mapLead(row: any): Lead {
  return {
    id: row.id,
    leadNumber: row.lead_number,
    createdAt: row.created_at,
    enquiryDate: row.enquiry_date,
    clientId: row.client_id ?? '',
    clientName: row.client_name ?? '',
    companyName: row.company_name ?? '',
    contactName: row.contact_name ?? '',
    phone: row.phone ?? '',
    email: row.email ?? '',
    source: row.source ?? 'WhatsApp',
    assignedTo: row.assigned_to ?? '',
    productId: row.product_id ?? '',
    productName: row.product_name ?? '',
    requestedQuantity: Number(row.requested_quantity ?? 0),
    dueDate: row.due_date ?? '',
    status: row.status ?? 'New',
    quickbooksEstimateNumber: row.quickbooks_estimate_number ?? '',
    linkedQuoteId: row.linked_quote_id ?? '',
    linkedQuoteNumber: row.linked_quote_number ?? '',
    notes: row.notes ?? '',
  };
}

function mapArtworkRecord(row: any): ArtworkRecord {
  return {
    id: row.id,
    artworkNumber: row.artwork_number,
    createdAt: row.created_at,
    jobId: row.job_id ?? '',
    jobNumber: row.job_number ?? '',
    clientId: row.client_id ?? '',
    clientName: row.client_name ?? '',
    artworkReceivedDate: row.artwork_received_date ?? '',
    proofSentDate: row.proof_sent_date ?? '',
    approvalDate: row.approval_date ?? '',
    stage: row.stage ?? 'Awaiting Artwork',
    changesRequested: row.changes_requested ?? '',
    notes: row.notes ?? '',
  };
}

function mapCustomerStockRelease(row: any): CustomerStockRelease {
  return {
    id: row.id,
    releaseNumber: row.release_number,
    createdAt: row.created_at,
    releaseDate: row.release_date,
    clientId: row.client_id ?? '',
    clientName: row.client_name ?? '',
    finishedGoodsStockId: row.finished_goods_stock_id ?? '',
    finishedGoodsStockNumber: row.finished_goods_stock_number ?? '',
    jobId: row.job_id ?? '',
    jobNumber: row.job_number ?? '',
    quantityReleased: Number(row.quantity_released ?? 0),
    quantityUnit: row.quantity_unit ?? 'units',
    destination: row.destination ?? '',
    notes: row.notes ?? '',
  };
}

function mapPricingTier(row: any): PricingTier {
  return {
    id: row.id,
    name: row.name,
    type: row.type,
    defaultMarginPercent: Number(row.default_margin_percent ?? 0),
    brandingMarginPercent: Number(row.branding_margin_percent ?? 0),
    notes: row.notes ?? '',
  };
}

function mapPaperRate(row: any): PaperRate {
  return {
    id: row.id,
    name: row.name,
    supplierId: row.supplier_id ?? '',
    supplierName: row.supplier_name ?? '',
    paperType: row.paper_type ?? '',
    gsm: row.gsm ?? '',
    pricePerTon: Number(row.price_per_ton ?? 0),
    notes: row.notes ?? '',
    active: row.active !== false,
  };
}

function mapCostProfile(row: any): CostProfile {
  return {
    id: row.id,
    name: row.name,
    wastagePercent: Number(row.wastage_percent ?? 0),
    defaultMarginPercent: Number(row.default_margin_percent ?? 0),
    baseGlueCostPerBag: Number(row.base_glue_cost_per_bag ?? 0),
    hotMeltCostPerBag: Number(row.hot_melt_cost_per_bag ?? 0),
    flatHandleCostPerBag: Number(row.flat_handle_cost_per_bag ?? 0),
    ropeHandleCostPerBag: Number(row.rope_handle_cost_per_bag ?? 0),
    rollHandleCostPerBag: Number(row.roll_handle_cost_per_bag ?? 0),
    screenPrintSetupCost: Number(row.screen_print_setup_cost ?? 0),
    screenPrintCostPerColor: Number(row.screen_print_cost_per_color ?? 0),
    flexoInkCostPer1000PerColor: Number(row.flexo_ink_cost_per_1000_per_color ?? 0),
    plateCostPerColor: Number(row.plate_cost_per_color ?? 0),
    labourCostPer1000: Number(row.labour_cost_per_1000 ?? 0),
    packagingCostPer1000: Number(row.packaging_cost_per_1000 ?? 0),
    transportCostPerJob: Number(row.transport_cost_per_job ?? 0),
    sideSeamAllowanceMm: Number(row.side_seam_allowance_mm ?? 0),
    topFoldAllowanceMm: Number(row.top_fold_allowance_mm ?? 0),
    bottomFoldAllowanceMm: Number(row.bottom_fold_allowance_mm ?? 0),
    flexoThresholdQty: Number(row.flexo_threshold_qty ?? 0),
    active: row.active !== false,
    notes: row.notes ?? '',
  };
}

function mapClient(row: any): Client {
  return {
    id: row.id,
    name: row.name,
    code: row.code ?? '',
    pricingTierId: row.pricing_tier_id ?? '',
    pricingTierName: row.pricing_tier_name ?? '',
    clientType: row.client_type ?? 'Wholesale',
    brandingDefault: Boolean(row.branding_default),
    defaultMarginPercent: Number(row.default_margin_percent ?? 0),
    creditLimit: Number(row.credit_limit ?? 0),
    currentBalance: Number(row.current_balance ?? 0),
    paymentTerms: row.payment_terms ?? '',
    accountHold: Boolean(row.account_hold),
    contactName: row.contact_name ?? '',
    contactEmail: row.contact_email ?? '',
    notes: row.notes ?? '',
    active: row.active !== false,
  };
}

function mapProduct(row: any): Product {
  return {
    id: row.id,
    name: row.name,
    sku: row.sku ?? '',
    category: row.category ?? 'Other Packaging',
    supplyType: row.supply_type ?? 'Purchased',
    defaultSupplierId: row.default_supplier_id ?? '',
    defaultSupplierName: row.default_supplier_name ?? '',
    brandingAllowed: Boolean(row.branding_allowed),
    defaultUnit: row.default_unit ?? 'units',
    defaultPaperType: row.default_paper_type ?? '',
    defaultGsm: row.default_gsm ?? '',
    notes: row.notes ?? '',
    active: row.active !== false,
  };
}

function mapJob(row: any): JobCard {
  return {
    id: row.id,
    jobNumber: row.job_number,
    createdAt: row.created_at,
    jobDate: row.job_date,
    dueDate: row.due_date ?? '',
    leadId: row.lead_id ?? '',
    leadNumber: row.lead_number ?? '',
    quoteId: row.quote_id ?? '',
    quoteNumber: row.quote_number_ref ?? '',
    quickbooksEstimateNumber: row.quickbooks_estimate_number ?? '',
    invoiceNumber: row.invoice_number ?? '',
    salesOwnerName: row.sales_owner_name ?? '',
    orderValue: Number(row.order_value ?? 0),
    paymentRequirement: row.payment_requirement ?? '50% Deposit',
    paymentStatus: row.payment_status ?? 'Pending',
    creditCheckStatus: row.credit_check_status ?? 'Not Required',
    availableCreditAtApproval: Number(row.available_credit_at_approval ?? 0),
    commercialReleaseStatus: row.commercial_release_status ?? 'Pending',
    clientId: row.client_id ?? '',
    pricingTierId: row.pricing_tier_id ?? '',
    productId: row.product_id ?? '',
    productCategory: row.product_category ?? 'Paper Bags',
    customerName: row.customer_name,
    customerReference: row.customer_reference ?? '',
    productName: row.product_name,
    description: row.description ?? '',
    sizeSpec: row.size_spec ?? '',
    paperType: row.paper_type ?? '',
    gsm: row.gsm ?? '',
    paperQuantityRequired: Number(row.paper_quantity_required ?? 0),
    paperQuantityUnit: row.paper_quantity_unit ?? 'kg',
    paperAllocationStatus: row.paper_allocation_status ?? 'Not Checked',
    linkedMaterialOrderId: row.linked_material_order_id ?? '',
    printRequired: Boolean(row.print_required),
    printMethod: row.print_method ?? 'Plain',
    colorCount: Number(row.color_count ?? 0),
    supplyFormat: row.supply_format ?? 'Boxes',
    packingNotes: row.packing_notes ?? '',
    printNotes: row.print_notes ?? '',
    quantityPlanned: Number(row.quantity_planned ?? 0),
    quantityCompleted: Number(row.quantity_completed ?? 0),
    status: row.status,
    artworkReceived: Boolean(row.artwork_received),
    proofSent: Boolean(row.proof_sent),
    approvalStatus: row.approval_status ?? 'Not Sent',
    approvalDate: row.approval_date ?? '',
    artworkPreparationStatus: row.artwork_preparation_status ?? 'Needs Design',
    addElementsRequired: Boolean(row.add_elements_required),
    colorChangesRequired: Boolean(row.color_changes_required),
    artworkChangeSummary: row.artwork_change_summary ?? '',
    artworkAssignedDate: row.artwork_assigned_date ?? '',
    artworkAssignedTo: row.artwork_assigned_to ?? '',
    proofSharedDate: row.proof_shared_date ?? '',
    proofSharedBy: row.proof_shared_by ?? '',
    finalApprovalReceivedDate: row.final_approval_received_date ?? '',
    finalApprovalClearedBy: row.final_approval_cleared_by ?? '',
    factoryReleaseDate: row.factory_release_date ?? '',
    factoryReleasedBy: row.factory_released_by ?? '',
    productionStartDate: row.production_start_date ?? '',
    productionStartedBy: row.production_started_by ?? '',
    readyForDispatchDate: row.ready_for_dispatch_date ?? '',
    readyForDispatchBy: row.ready_for_dispatch_by ?? '',
    collectionOrDeliveryStatus: row.collection_or_delivery_status ?? 'Not Confirmed',
    changesRequested: row.changes_requested ?? '',
    artworkNotes: row.artwork_notes ?? '',
    reserveFromStock: Boolean(row.reserve_from_stock),
    reservedFinishedGoodsStockId: row.reserved_finished_goods_stock_id ?? '',
    reservedFinishedGoodsStockNumber: row.reserved_finished_goods_stock_number ?? '',
    reservedQuantity: Number(row.reserved_quantity ?? 0),
    stockReservationStatus: row.stock_reservation_status ?? 'Not Checked',
    dispatchStatus: row.dispatch_status ?? '',
    qualityNotes: row.quality_notes ?? '',
    capturedBy: row.captured_by ?? '',
    releasedBy: row.released_by ?? '',
    notes: row.notes ?? '',
    fscRelated: Boolean(row.fsc_related),
  };
}

function mapMaterialOrderRequest(row: any): MaterialOrderRequest {
  return {
    id: row.id,
    orderNumber: row.order_number,
    createdAt: row.created_at,
    requestedDate: row.requested_date ?? '',
    status: row.status ?? 'Requested',
    jobId: row.job_id ?? '',
    jobNumber: row.job_number ?? '',
    clientId: row.client_id ?? '',
    clientName: row.client_name ?? '',
    productId: row.product_id ?? '',
    productName: row.product_name ?? '',
    paperType: row.paper_type ?? '',
    gsm: row.gsm ?? '',
    quantityRequired: Number(row.quantity_required ?? 0),
    quantityUnit: row.quantity_unit ?? 'kg',
    shortageQuantity: Number(row.shortage_quantity ?? 0),
    supplierId: row.supplier_id ?? '',
    supplierName: row.supplier_name ?? '',
    requestedBy: row.requested_by ?? '',
    notes: row.notes ?? '',
  };
}

function mapFinishedGoodsStock(row: any): FinishedGoodsStock {
  return {
    id: row.id,
    stockNumber: row.stock_number,
    createdAt: row.created_at,
    storedDate: row.stored_date,
    productId: row.product_id ?? '',
    productName: row.product_name ?? '',
    clientId: row.client_id ?? '',
    clientName: row.client_name ?? '',
    jobId: row.job_id ?? '',
    jobNumber: row.job_number ?? '',
    quantityOnHand: Number(row.quantity_on_hand ?? 0),
    quantityReserved: Number(row.quantity_reserved ?? 0),
    quantityAvailable: Number(row.quantity_available ?? 0),
    quantityUnit: row.quantity_unit ?? 'units',
    storageLocation: row.storage_location ?? '',
    stockStatus: row.stock_status ?? 'In Storage',
    brandingStatus: row.branding_status ?? '',
    notes: row.notes ?? '',
  };
}

function mapStockChangeLog(row: any): StockChangeLog {
  return {
    id: row.id,
    createdAt: row.created_at,
    finishedGoodsStockId: row.finished_goods_stock_id ?? '',
    stockNumber: row.stock_number ?? '',
    productName: row.product_name ?? '',
    action: row.action ?? 'updated',
    changedByUserId: row.changed_by_user_id ?? '',
    changedByName: row.changed_by_name ?? '',
    previousQuantityOnHand: Number(row.previous_quantity_on_hand ?? 0),
    nextQuantityOnHand: Number(row.next_quantity_on_hand ?? 0),
    previousQuantityReserved: Number(row.previous_quantity_reserved ?? 0),
    nextQuantityReserved: Number(row.next_quantity_reserved ?? 0),
    notes: row.notes ?? '',
  };
}

function mapSparePart(row: any): SparePart {
  return {
    id: row.id,
    partCode: row.part_code,
    createdAt: row.created_at,
    partName: row.part_name,
    category: row.category ?? '',
    machineId: row.machine_id ?? '',
    machineReference: row.machine_reference ?? '',
    supplierId: row.supplier_id ?? '',
    supplierName: row.supplier_name ?? '',
    quantityOnHand: Number(row.quantity_on_hand ?? 0),
    minimumStockLevel: Number(row.minimum_stock_level ?? 0),
    reorderLevel: Number(row.reorder_level ?? 0),
    unitOfMeasure: row.unit_of_measure ?? 'units',
    unitCost: Number(row.unit_cost ?? 0),
    storageLocation: row.storage_location ?? '',
    lastPurchaseDate: row.last_purchase_date ?? '',
    notes: row.notes ?? '',
  };
}

function mapMaterialReceipt(row: any): MaterialReceipt {
  return {
    id: row.id,
    receiptNumber: row.receipt_number,
    createdAt: row.created_at,
    receivedDate: row.received_date,
    supplierId: row.supplier_id ?? '',
    supplierName: row.supplier_name,
    supplierBatchNumber: row.supplier_batch_number ?? '',
    internalRollCode: row.internal_roll_code,
    paperType: row.paper_type ?? '',
    gsm: row.gsm ?? '',
    width: row.width ?? '',
    quantityReceived: Number(row.quantity_received ?? 0),
    quantityUnit: row.quantity_unit,
    fscClaimType: row.fsc_claim_type ?? 'None',
    supplierCertificateCode: row.supplier_certificate_code ?? '',
    invoiceReference: row.invoice_reference ?? '',
    storageLocation: row.storage_location ?? '',
    inspectionNotes: row.inspection_notes ?? '',
    fscRelated: Boolean(row.fsc_related),
  };
}

function mapProductionLog(row: any): ProductionLogEntry {
  return {
    id: row.id,
    logNumber: row.log_number,
    createdAt: row.created_at,
    logDate: row.log_date,
    logType: row.log_type,
    jobId: row.job_id ?? '',
    jobNumber: row.job_number ?? '',
    customerName: row.customer_name ?? '',
    operatorName: row.operator_name ?? '',
    machineId: row.machine_id ?? '',
    machine: row.machine ?? '',
    sourceMaterialId: row.source_material_id ?? '',
    sourceMaterialCode: row.source_material_code ?? '',
    setupTimeMinutes: Number(row.setup_time_minutes ?? 0),
    notes: row.notes ?? '',
    operatorSignature: row.operator_signature ?? '',
    fscRelated: Boolean(row.fsc_related),
    rollCode: row.roll_code ?? '',
    height: row.height ?? '',
    gusset: row.gusset ?? '',
    handleType: row.handle_type ?? '',
    goodBags: Number(row.good_bags ?? 0),
    rejectBags: Number(row.reject_bags ?? 0),
    heightChange: row.height_change ?? '',
    printingMethod: row.printing_method ?? '',
    bagSize: row.bag_size ?? '',
    numberOfColors: Number(row.number_of_colors ?? 0),
    quantityPrinted: Number(row.quantity_printed ?? 0),
    materialSourceCode: row.material_source_code ?? '',
    rollWidth: row.roll_width ?? '',
    metersKgPrinted: Number(row.meters_kg_printed ?? 0),
    rejectMetersKg: Number(row.reject_meters_kg ?? 0),
    parentRollCode: row.parent_roll_code ?? '',
    parentWidth: row.parent_width ?? '',
    targetChildWidth: row.target_child_width ?? '',
    numberOfChildRolls: Number(row.number_of_child_rolls ?? 0),
    childDiameter: row.child_diameter ?? '',
    totalWasteKg: Number(row.total_waste_kg ?? 0),
    bladeChange: row.blade_change ?? '',
  };
}

function mapWaste(row: any): WasteEntry {
  return {
    id: row.id,
    wasteNumber: row.waste_number,
    createdAt: row.created_at,
    wasteDate: row.waste_date,
    jobId: row.job_id ?? '',
    jobNumber: row.job_number ?? '',
    customerName: row.customer_name ?? '',
    productName: row.product_name ?? '',
    productionLogId: row.production_log_id ?? '',
    productionLogNumber: row.production_log_number ?? '',
    wasteQuantity: Number(row.waste_quantity ?? 0),
    wasteUnit: row.waste_unit,
    wasteReason: row.waste_reason,
    notes: row.notes ?? '',
    enteredBy: row.entered_by ?? '',
    fscRelated: Boolean(row.fsc_related),
  };
}

function mapPaper(row: any): PaperLog {
  return {
    id: row.id,
    paperLogNumber: row.paper_log_number,
    createdAt: row.created_at,
    logDate: row.log_date,
    jobId: row.job_id ?? '',
    jobNumber: row.job_number ?? '',
    customerName: row.customer_name ?? '',
    materialReceiptId: row.material_receipt_id ?? '',
    materialReceiptNumber: row.material_receipt_number ?? '',
    paperType: row.paper_type,
    gsm: row.gsm ?? '',
    width: row.width ?? '',
    quantityUsed: Number(row.quantity_used ?? 0),
    quantityUnit: row.quantity_unit,
    paperCode: row.paper_code ?? '',
    notes: row.notes ?? '',
    fscRelated: Boolean(row.fsc_related),
  };
}

function mapDispatch(row: any): DispatchRecord {
  return {
    id: row.id,
    dispatchNumber: row.dispatch_number,
    createdAt: row.created_at,
    dispatchDate: row.dispatch_date,
    jobId: row.job_id ?? '',
    jobNumber: row.job_number ?? '',
    customerName: row.customer_name ?? '',
    finishedGoodsStockId: row.finished_goods_stock_id ?? '',
    finishedGoodsStockNumber: row.finished_goods_stock_number ?? '',
    quantityDispatched: Number(row.quantity_dispatched ?? 0),
    quantityUnit: row.quantity_unit,
    labelReference: row.label_reference ?? '',
    deliveryReference: row.delivery_reference ?? '',
    issueNotes: row.issue_notes ?? '',
    fscRelated: Boolean(row.fsc_related),
  };
}

export async function fetchAppData(): Promise<AppData> {
  const [
    suppliers,
    machines,
    leads,
    quoteEstimates,
    artworkRecords,
    customerStockReleases,
    paperRates,
    costProfiles,
    pricingTiers,
    clients,
    products,
    jobs,
    finishedGoodsStock,
    spareParts,
    materialReceipts,
    productionLogs,
    wasteEntries,
    paperLogs,
    dispatchRecords,
    stockChangeLogs,
    materialOrderRequests,
  ] = await Promise.all([
    safeSelect('suppliers'),
    safeSelect('machines'),
    safeSelect('leads'),
    safeSelect('quote_estimates'),
    safeSelect('artwork_records'),
    safeSelect('customer_stock_releases'),
    safeSelect('paper_rates'),
    safeSelect('cost_profiles'),
    safeSelect('pricing_tiers'),
    safeSelect('clients'),
    safeSelect('products'),
    safeSelect('jobs'),
    safeSelect('finished_goods_stock'),
    safeSelect('spare_parts'),
    safeSelect('material_receipts'),
    safeSelect('production_logs'),
    safeSelect('waste_entries'),
    safeSelect('paper_logs'),
    safeSelect('dispatch_records'),
    safeSelect('stock_change_logs'),
    safeSelect('material_order_requests'),
  ]);

  return {
    suppliers: suppliers.map(mapSupplier),
    machines: machines.map(mapMachine),
    leads: leads.map(mapLead),
    quoteEstimates: quoteEstimates.map(mapQuoteEstimate),
    artworkRecords: artworkRecords.map(mapArtworkRecord),
    customerStockReleases: customerStockReleases.map(mapCustomerStockRelease),
    paperRates: paperRates.map(mapPaperRate),
    costProfiles: costProfiles.map(mapCostProfile),
    pricingTiers: pricingTiers.map(mapPricingTier),
    clients: clients.map(mapClient),
    products: products.map(mapProduct),
    jobs: jobs.map(mapJob),
    finishedGoodsStock: finishedGoodsStock.map(mapFinishedGoodsStock),
    spareParts: spareParts.map(mapSparePart),
    materialReceipts: materialReceipts.map(mapMaterialReceipt),
    productionLogs: productionLogs.map(mapProductionLog),
    wasteEntries: wasteEntries.map(mapWaste),
    paperLogs: paperLogs.map(mapPaper),
    dispatchRecords: dispatchRecords.map(mapDispatch),
    stockChangeLogs: stockChangeLogs.map(mapStockChangeLog),
    materialOrderRequests: materialOrderRequests.map(mapMaterialOrderRequest),
  };
}

export async function syncAppData(data: AppData): Promise<void> {
  await Promise.all([
    safeUpsert('suppliers', data.suppliers.map((supplier) => ({
      id: supplier.id,
      name: supplier.name,
      contact_person: supplier.contactPerson || null,
      phone: supplier.phone || null,
      email: supplier.email || null,
      contacts: supplier.contacts,
      address: supplier.address || null,
      billing_address: supplier.billingAddress || null,
      city: supplier.city || null,
      country: supplier.country || null,
      website: supplier.website || null,
      supplier_type: supplier.supplierType,
      certificate_code: supplier.certificateCode || null,
      account_number: supplier.accountNumber || null,
      payment_terms: supplier.paymentTerms || null,
      credit_limit: supplier.creditLimit,
      current_balance: supplier.currentBalance,
      currency: supplier.currency,
      is_also_client: supplier.isAlsoClient,
      linked_client_id: supplier.linkedClientId || null,
      linked_client_name: supplier.linkedClientName || null,
      last_check_in_date: supplier.lastCheckInDate || null,
      next_review_date: supplier.nextReviewDate || null,
      review_frequency_months: supplier.reviewFrequencyMonths,
      internal_owner: supplier.internalOwner || null,
      certifications: supplier.certifications,
      supplied_products: supplier.suppliedProducts,
      notes: supplier.notes || null,
      active: supplier.active,
    }))),
    safeUpsert('machines', data.machines.map((machine) => ({
      id: machine.id,
      name: machine.name,
      code: machine.code || null,
      department: machine.department || null,
      process_type: machine.processType || null,
      status: machine.status,
      notes: machine.notes || null,
      active: machine.active,
    }))),
    safeUpsert('leads', data.leads.map((lead) => ({
      id: lead.id,
      lead_number: lead.leadNumber,
      created_at: lead.createdAt,
      enquiry_date: lead.enquiryDate,
      client_id: lead.clientId || null,
      client_name: lead.clientName || null,
      company_name: lead.companyName || null,
      contact_name: lead.contactName || null,
      phone: lead.phone || null,
      email: lead.email || null,
      source: lead.source,
      assigned_to: lead.assignedTo || null,
      product_id: lead.productId || null,
      product_name: lead.productName || null,
      requested_quantity: lead.requestedQuantity,
      due_date: lead.dueDate || null,
      status: lead.status,
      quickbooks_estimate_number: lead.quickbooksEstimateNumber || null,
      linked_quote_id: lead.linkedQuoteId || null,
      linked_quote_number: lead.linkedQuoteNumber || null,
      notes: lead.notes || null,
    }))),
    safeUpsert('quote_estimates', data.quoteEstimates.map((quote) => ({
      id: quote.id,
      quote_number: quote.quoteNumber,
      quickbooks_estimate_number: quote.quickbooksEstimateNumber || null,
      created_at: quote.createdAt,
      quote_date: quote.quoteDate,
      linked_lead_id: quote.linkedLeadId || null,
      linked_lead_number: quote.linkedLeadNumber || null,
      sales_owner_name: quote.salesOwnerName || null,
      client_id: quote.clientId || null,
      client_name: quote.clientName || null,
      product_id: quote.productId || null,
      product_name: quote.productName || null,
      pricing_tier_id: quote.pricingTierId || null,
      pricing_tier_name: quote.pricingTierName || null,
      paper_rate_id: quote.paperRateId || null,
      paper_rate_name: quote.paperRateName || null,
      cost_profile_id: quote.costProfileId || null,
      cost_profile_name: quote.costProfileName || null,
      quantity: quote.quantity,
      size_spec: quote.sizeSpec || null,
      handle_type: quote.handleType,
      print_method: quote.printMethod,
      colors: quote.colors,
      unit_cost: quote.unitCost,
      quoted_unit_price: quote.quotedUnitPrice,
      total_quote: quote.totalQuote,
      status: quote.status,
      notes: quote.notes || null,
    }))),
    safeUpsert('artwork_records', data.artworkRecords.map((artwork) => ({
      id: artwork.id,
      artwork_number: artwork.artworkNumber,
      created_at: artwork.createdAt,
      job_id: artwork.jobId || null,
      job_number: artwork.jobNumber || null,
      client_id: artwork.clientId || null,
      client_name: artwork.clientName || null,
      artwork_received_date: artwork.artworkReceivedDate || null,
      proof_sent_date: artwork.proofSentDate || null,
      approval_date: artwork.approvalDate || null,
      stage: artwork.stage,
      changes_requested: artwork.changesRequested || null,
      notes: artwork.notes || null,
    }))),
    safeUpsert('customer_stock_releases', data.customerStockReleases.map((release) => ({
      id: release.id,
      release_number: release.releaseNumber,
      created_at: release.createdAt,
      release_date: release.releaseDate,
      client_id: release.clientId || null,
      client_name: release.clientName || null,
      finished_goods_stock_id: release.finishedGoodsStockId || null,
      finished_goods_stock_number: release.finishedGoodsStockNumber || null,
      job_id: release.jobId || null,
      job_number: release.jobNumber || null,
      quantity_released: release.quantityReleased,
      quantity_unit: release.quantityUnit,
      destination: release.destination || null,
      notes: release.notes || null,
    }))),
    safeUpsert('paper_rates', data.paperRates.map((rate) => ({
      id: rate.id,
      name: rate.name,
      supplier_id: rate.supplierId || null,
      supplier_name: rate.supplierName || null,
      paper_type: rate.paperType || null,
      gsm: rate.gsm || null,
      price_per_ton: rate.pricePerTon,
      notes: rate.notes || null,
      active: rate.active,
    }))),
    safeUpsert('cost_profiles', data.costProfiles.map((profile) => ({
      id: profile.id,
      name: profile.name,
      wastage_percent: profile.wastagePercent,
      default_margin_percent: profile.defaultMarginPercent,
      base_glue_cost_per_bag: profile.baseGlueCostPerBag,
      hot_melt_cost_per_bag: profile.hotMeltCostPerBag,
      flat_handle_cost_per_bag: profile.flatHandleCostPerBag,
      rope_handle_cost_per_bag: profile.ropeHandleCostPerBag,
      roll_handle_cost_per_bag: profile.rollHandleCostPerBag,
      screen_print_setup_cost: profile.screenPrintSetupCost,
      screen_print_cost_per_color: profile.screenPrintCostPerColor,
      flexo_ink_cost_per_1000_per_color: profile.flexoInkCostPer1000PerColor,
      plate_cost_per_color: profile.plateCostPerColor,
      labour_cost_per_1000: profile.labourCostPer1000,
      packaging_cost_per_1000: profile.packagingCostPer1000,
      transport_cost_per_job: profile.transportCostPerJob,
      side_seam_allowance_mm: profile.sideSeamAllowanceMm,
      top_fold_allowance_mm: profile.topFoldAllowanceMm,
      bottom_fold_allowance_mm: profile.bottomFoldAllowanceMm,
      flexo_threshold_qty: profile.flexoThresholdQty,
      active: profile.active,
      notes: profile.notes || null,
    }))),
    safeUpsert('pricing_tiers', data.pricingTiers.map((tier) => ({
      id: tier.id,
      name: tier.name,
      type: tier.type,
      default_margin_percent: tier.defaultMarginPercent,
      branding_margin_percent: tier.brandingMarginPercent,
      notes: tier.notes || null,
    }))),
    safeUpsert('clients', data.clients.map((client) => ({
      id: client.id,
      name: client.name,
      code: client.code || null,
      pricing_tier_id: client.pricingTierId || null,
      pricing_tier_name: client.pricingTierName || null,
      client_type: client.clientType,
      branding_default: client.brandingDefault,
      default_margin_percent: client.defaultMarginPercent,
      credit_limit: client.creditLimit,
      current_balance: client.currentBalance,
      payment_terms: client.paymentTerms || null,
      account_hold: client.accountHold,
      contact_name: client.contactName || null,
      contact_email: client.contactEmail || null,
      notes: client.notes || null,
      active: client.active,
    }))),
    safeUpsert('products', data.products.map((product) => ({
      id: product.id,
      name: product.name,
      sku: product.sku || null,
      category: product.category,
      supply_type: product.supplyType,
      default_supplier_id: product.defaultSupplierId || null,
      default_supplier_name: product.defaultSupplierName || null,
      branding_allowed: product.brandingAllowed,
      default_unit: product.defaultUnit,
      default_paper_type: product.defaultPaperType || null,
      default_gsm: product.defaultGsm || null,
      notes: product.notes || null,
      active: product.active,
    }))),
    safeUpsert('jobs', data.jobs.map((job) => ({
      id: job.id,
      job_number: job.jobNumber,
      created_at: job.createdAt,
      job_date: job.jobDate,
      due_date: job.dueDate || null,
      lead_id: job.leadId || null,
      lead_number: job.leadNumber || null,
      quote_id: job.quoteId || null,
      quote_number_ref: job.quoteNumber || null,
      quickbooks_estimate_number: job.quickbooksEstimateNumber || null,
      invoice_number: job.invoiceNumber || null,
      sales_owner_name: job.salesOwnerName || null,
      order_value: job.orderValue,
      payment_requirement: job.paymentRequirement,
      payment_status: job.paymentStatus,
      credit_check_status: job.creditCheckStatus,
      available_credit_at_approval: job.availableCreditAtApproval,
      commercial_release_status: job.commercialReleaseStatus,
      client_id: job.clientId || null,
      pricing_tier_id: job.pricingTierId || null,
      product_id: job.productId || null,
      product_category: job.productCategory,
      customer_name: job.customerName,
      customer_reference: job.customerReference || null,
      product_name: job.productName,
      description: job.description || null,
      size_spec: job.sizeSpec || null,
      paper_type: job.paperType || null,
      gsm: job.gsm || null,
      paper_quantity_required: job.paperQuantityRequired,
      paper_quantity_unit: job.paperQuantityUnit,
      paper_allocation_status: job.paperAllocationStatus,
      linked_material_order_id: job.linkedMaterialOrderId || null,
      print_required: job.printRequired,
      print_method: job.printMethod,
      color_count: job.colorCount,
      supply_format: job.supplyFormat,
      packing_notes: job.packingNotes || null,
      print_notes: job.printNotes || null,
      quantity_planned: job.quantityPlanned,
      quantity_completed: job.quantityCompleted,
      status: job.status,
      artwork_received: job.artworkReceived,
      proof_sent: job.proofSent,
      approval_status: job.approvalStatus,
      approval_date: job.approvalDate || null,
      artwork_preparation_status: job.artworkPreparationStatus,
      add_elements_required: job.addElementsRequired,
      color_changes_required: job.colorChangesRequired,
      artwork_change_summary: job.artworkChangeSummary || null,
      artwork_assigned_date: job.artworkAssignedDate || null,
      artwork_assigned_to: job.artworkAssignedTo || null,
      proof_shared_date: job.proofSharedDate || null,
      proof_shared_by: job.proofSharedBy || null,
      final_approval_received_date: job.finalApprovalReceivedDate || null,
      final_approval_cleared_by: job.finalApprovalClearedBy || null,
      factory_release_date: job.factoryReleaseDate || null,
      factory_released_by: job.factoryReleasedBy || null,
      production_start_date: job.productionStartDate || null,
      production_started_by: job.productionStartedBy || null,
      ready_for_dispatch_date: job.readyForDispatchDate || null,
      ready_for_dispatch_by: job.readyForDispatchBy || null,
      collection_or_delivery_status: job.collectionOrDeliveryStatus,
      changes_requested: job.changesRequested || null,
      artwork_notes: job.artworkNotes || null,
      reserve_from_stock: job.reserveFromStock,
      reserved_finished_goods_stock_id: job.reservedFinishedGoodsStockId || null,
      reserved_finished_goods_stock_number: job.reservedFinishedGoodsStockNumber || null,
      reserved_quantity: job.reservedQuantity,
      stock_reservation_status: job.stockReservationStatus,
      dispatch_status: job.dispatchStatus || null,
      quality_notes: job.qualityNotes || null,
      captured_by: job.capturedBy || null,
      released_by: job.releasedBy || null,
      notes: job.notes || null,
      fsc_related: job.fscRelated,
    }))),
    safeUpsert('material_order_requests', data.materialOrderRequests.map((request) => ({
      id: request.id,
      order_number: request.orderNumber,
      created_at: request.createdAt,
      requested_date: request.requestedDate,
      status: request.status,
      job_id: request.jobId || null,
      job_number: request.jobNumber || null,
      client_id: request.clientId || null,
      client_name: request.clientName || null,
      product_id: request.productId || null,
      product_name: request.productName || null,
      paper_type: request.paperType || null,
      gsm: request.gsm || null,
      quantity_required: request.quantityRequired,
      quantity_unit: request.quantityUnit,
      shortage_quantity: request.shortageQuantity,
      supplier_id: request.supplierId || null,
      supplier_name: request.supplierName || null,
      requested_by: request.requestedBy || null,
      notes: request.notes || null,
    }))),
    safeUpsert('finished_goods_stock', data.finishedGoodsStock.map((item) => ({
      id: item.id,
      stock_number: item.stockNumber,
      created_at: item.createdAt,
      stored_date: item.storedDate,
      product_id: item.productId || null,
      product_name: item.productName,
      client_id: item.clientId || null,
      client_name: item.clientName || null,
      job_id: item.jobId || null,
      job_number: item.jobNumber || null,
      quantity_on_hand: item.quantityOnHand,
      quantity_reserved: item.quantityReserved,
      quantity_available: item.quantityAvailable,
      quantity_unit: item.quantityUnit,
      storage_location: item.storageLocation || null,
      stock_status: item.stockStatus,
      branding_status: item.brandingStatus || null,
      notes: item.notes || null,
    }))),
    safeUpsert('spare_parts', data.spareParts.map((part) => ({
      id: part.id,
      part_code: part.partCode,
      created_at: part.createdAt,
      part_name: part.partName,
      category: part.category || null,
      machine_id: part.machineId || null,
      machine_reference: part.machineReference || null,
      supplier_id: part.supplierId || null,
      supplier_name: part.supplierName || null,
      quantity_on_hand: part.quantityOnHand,
      minimum_stock_level: part.minimumStockLevel,
      reorder_level: part.reorderLevel,
      unit_of_measure: part.unitOfMeasure,
      unit_cost: part.unitCost,
      storage_location: part.storageLocation || null,
      last_purchase_date: part.lastPurchaseDate || null,
      notes: part.notes || null,
    }))),
    safeUpsert('material_receipts', data.materialReceipts.map((receipt) => ({
      id: receipt.id,
      receipt_number: receipt.receiptNumber,
      created_at: receipt.createdAt,
      received_date: receipt.receivedDate,
      supplier_id: receipt.supplierId || null,
      supplier_name: receipt.supplierName,
      supplier_batch_number: receipt.supplierBatchNumber || null,
      internal_roll_code: receipt.internalRollCode,
      paper_type: receipt.paperType || null,
      gsm: receipt.gsm || null,
      width: receipt.width || null,
      quantity_received: receipt.quantityReceived,
      quantity_unit: receipt.quantityUnit,
      fsc_claim_type: receipt.fscClaimType,
      supplier_certificate_code: receipt.supplierCertificateCode || null,
      invoice_reference: receipt.invoiceReference || null,
      storage_location: receipt.storageLocation || null,
      inspection_notes: receipt.inspectionNotes || null,
      fsc_related: receipt.fscRelated,
    }))),
    safeUpsert('production_logs', data.productionLogs.map((log) => ({
      id: log.id,
      log_number: log.logNumber,
      created_at: log.createdAt,
      log_date: log.logDate,
      log_type: log.logType,
      job_id: log.jobId || null,
      job_number: log.jobNumber || null,
      customer_name: log.customerName || null,
      operator_name: log.operatorName || null,
      machine_id: log.machineId || null,
      machine: log.machine || null,
      source_material_id: log.sourceMaterialId || null,
      source_material_code: log.sourceMaterialCode || null,
      setup_time_minutes: log.setupTimeMinutes,
      notes: log.notes || null,
      operator_signature: log.operatorSignature || null,
      fsc_related: log.fscRelated,
      roll_code: log.rollCode || null,
      height: log.height || null,
      gusset: log.gusset || null,
      handle_type: log.handleType || null,
      good_bags: log.goodBags,
      reject_bags: log.rejectBags,
      height_change: log.heightChange || null,
      printing_method: log.printingMethod || null,
      bag_size: log.bagSize || null,
      number_of_colors: log.numberOfColors,
      quantity_printed: log.quantityPrinted,
      material_source_code: log.materialSourceCode || null,
      roll_width: log.rollWidth || null,
      meters_kg_printed: log.metersKgPrinted,
      reject_meters_kg: log.rejectMetersKg,
      parent_roll_code: log.parentRollCode || null,
      parent_width: log.parentWidth || null,
      target_child_width: log.targetChildWidth || null,
      number_of_child_rolls: log.numberOfChildRolls,
      child_diameter: log.childDiameter || null,
      total_waste_kg: log.totalWasteKg,
      blade_change: log.bladeChange || null,
    }))),
    safeUpsert('waste_entries', data.wasteEntries.map((entry) => ({
      id: entry.id,
      waste_number: entry.wasteNumber,
      created_at: entry.createdAt,
      waste_date: entry.wasteDate,
      job_id: entry.jobId || null,
      job_number: entry.jobNumber || null,
      customer_name: entry.customerName || null,
      product_name: entry.productName || null,
      production_log_id: entry.productionLogId || null,
      production_log_number: entry.productionLogNumber || null,
      waste_quantity: entry.wasteQuantity,
      waste_unit: entry.wasteUnit,
      waste_reason: entry.wasteReason,
      notes: entry.notes || null,
      entered_by: entry.enteredBy || null,
      fsc_related: entry.fscRelated,
    }))),
    safeUpsert('paper_logs', data.paperLogs.map((log) => ({
      id: log.id,
      paper_log_number: log.paperLogNumber,
      created_at: log.createdAt,
      log_date: log.logDate,
      job_id: log.jobId || null,
      job_number: log.jobNumber || null,
      customer_name: log.customerName || null,
      material_receipt_id: log.materialReceiptId || null,
      material_receipt_number: log.materialReceiptNumber || null,
      paper_type: log.paperType,
      gsm: log.gsm || null,
      width: log.width || null,
      quantity_used: log.quantityUsed,
      quantity_unit: log.quantityUnit,
      paper_code: log.paperCode || null,
      notes: log.notes || null,
      fsc_related: log.fscRelated,
    }))),
    safeUpsert('dispatch_records', data.dispatchRecords.map((record) => ({
      id: record.id,
      dispatch_number: record.dispatchNumber,
      created_at: record.createdAt,
      dispatch_date: record.dispatchDate,
      job_id: record.jobId || null,
      job_number: record.jobNumber || null,
      customer_name: record.customerName || null,
      finished_goods_stock_id: record.finishedGoodsStockId || null,
      finished_goods_stock_number: record.finishedGoodsStockNumber || null,
      quantity_dispatched: record.quantityDispatched,
      quantity_unit: record.quantityUnit,
      label_reference: record.labelReference || null,
      delivery_reference: record.deliveryReference || null,
      issue_notes: record.issueNotes || null,
      fsc_related: record.fscRelated,
    }))),
    safeUpsert('stock_change_logs', data.stockChangeLogs.map((log) => ({
      id: log.id,
      created_at: log.createdAt,
      finished_goods_stock_id: log.finishedGoodsStockId || null,
      stock_number: log.stockNumber || null,
      product_name: log.productName || null,
      action: log.action,
      changed_by_user_id: log.changedByUserId || null,
      changed_by_name: log.changedByName || null,
      previous_quantity_on_hand: log.previousQuantityOnHand,
      next_quantity_on_hand: log.nextQuantityOnHand,
      previous_quantity_reserved: log.previousQuantityReserved,
      next_quantity_reserved: log.nextQuantityReserved,
      notes: log.notes || null,
    }))),
  ]);
}
